version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: workshop_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: workshopdb
      MYSQL_USER: workshopuser
      MYSQL_PASSWORD: 250601
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
